CREATE TABLE BUSLOCATION (
    CROWDED       CHAR(1),
    LOWPLATE      CHAR(1),
    PLATENO       VARCHAR2(30),
    REMAINSEATCNT VARCHAR2(10),
    ROUTEID       VARCHAR2(20),
    ROUTETYPECD   VARCHAR2(10),
    STATECD       CHAR(1),
    STATIONID     VARCHAR2(20),
    STATIONSEQ    VARCHAR2(10),
    TAGLESSCD     CHAR(1),
    VEHID         VARCHAR2(30),
    CONSTRAINT PK_BUSLOCATION PRIMARY KEY ( PLATENO, VEHID )
);

COMMENT ON TABLE BUSLOCATION IS '경기도_버스위치정보';

COMMENT ON COLUMN BUSLOCATION.CROWDED IS '혼잡도';

COMMENT ON COLUMN BUSLOCATION.LOWPLATE IS '저상버스 여부';

COMMENT ON COLUMN BUSLOCATION.PLATENO IS '차량 번호판';

COMMENT ON COLUMN BUSLOCATION.REMAINSEATCNT IS '남은 좌석 수';

COMMENT ON COLUMN BUSLOCATION.ROUTEID IS '버스 노선 ID';

COMMENT ON COLUMN BUSLOCATION.ROUTETYPECD IS '노선 유형 코드';

COMMENT ON COLUMN BUSLOCATION.STATECD IS '차량 상태 코드';

COMMENT ON COLUMN BUSLOCATION.STATIONID IS '정류장 ID';

COMMENT ON COLUMN BUSLOCATION.STATIONSEQ IS '노선 내 정류장 순번';

COMMENT ON COLUMN BUSLOCATION.TAGLESSCD IS '태그 없는 승차 여부';

COMMENT ON COLUMN BUSLOCATION.VEHID IS '차량 고유 ID';